'use client'

import Image from 'next/image'
import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronDown, Heart, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, UserRound, X } from 'lucide-react'

const categories = [
  { name: 'Peixes marinhos', count: '42 espécies', image: '/images/category-fish.png', query: 'peixes' },
  { name: 'Corais premium', count: '86 variedades', image: '/images/category-coral.png', query: 'coral' },
  { name: 'Invertebrados', count: '24 espécies', image: '/images/reef-hero.png', query: 'invertebrados' },
  { name: 'Equipamentos', count: '120 produtos', image: '/images/category-equipment.png', query: 'equipamentos' },
  { name: 'Química da água', count: '35 soluções', image: '/images/category-equipment.png', query: 'química' },
  { name: 'Aquários reef', count: '18 projetos', image: '/images/reef-hero.png', query: 'aquários' },
]

const products = [
  { name: 'Ocellaris Clownfish', detail: 'Amphiprion ocellaris · Captive bred', price: '€ 39,90', image: '/images/category-fish.png', tag: 'Mais procurado', category: 'peixes', id: 'clownfish' },
  { name: 'Acropora Ultra Violet', detail: 'SPS coral · WYSIWYG frag', price: '€ 89,00', image: '/images/category-coral.png', tag: 'Novo', category: 'coral', id: 'acropora' },
  { name: 'Reef LED Aurora 60', detail: 'Iluminação inteligente · 60W', price: '€ 249,00', image: '/images/category-equipment.png', tag: 'Seleção REEF GALLERY', category: 'equipamentos', id: 'aurora-led' },
]

type Product = (typeof products)[number]
type CartLine = { product: Product; quantity: number }

// Substitua por uma URL MP4 real quando o vídeo final estiver disponível.
const HERO_VIDEO_URL = ''

const languages = [{ code: 'PT', label: 'Português' }, { code: 'EN', label: 'English' }, { code: 'ES', label: 'Español' }, { code: 'FR', label: 'Français' }, { code: 'DE', label: 'Deutsch' }, { code: 'IT', label: 'Italiano' }]
const translations = {
  PT: { shop: 'Loja', categories: 'Categorias', essentials: 'Essenciais do reef', journal: 'Journal', heroEyebrow: 'Mais do que um hobby', heroTitle: 'O oceano, na sua casa.', heroBody: 'Peixes, corais e tudo o que precisa para criar um reef saudável, com qualidade e confiança.', explore: 'Explorar a coleção', story: 'Conheça a REEF GALLERY', search: 'O que procura para o seu reef?', freeShipping: 'Portes grátis a partir de € 99', account: 'Área do cliente', cart: 'Carrinho', empty: 'O seu carrinho está vazio.' },
  EN: { shop: 'Shop', categories: 'Categories', essentials: 'Reef essentials', journal: 'Journal', heroEyebrow: 'More than a hobby', heroTitle: 'The ocean, at home.', heroBody: 'Fish, corals and everything you need to create a healthy reef with quality and confidence.', explore: 'Explore the collection', story: 'Discover REEF GALLERY', search: 'What are you looking for?', freeShipping: 'Free shipping from €99', account: 'Customer area', cart: 'Cart', empty: 'Your cart is empty.' },
  ES: { shop: 'Tienda', categories: 'Categorías', essentials: 'Esenciales del reef', journal: 'Journal', heroEyebrow: 'Más que un hobby', heroTitle: 'El océano, en casa.', heroBody: 'Peces, corales y todo lo que necesitas para crear un reef saludable.', explore: 'Explorar la colección', story: 'Conoce REEF GALLERY', search: '¿Qué buscas para tu reef?', freeShipping: 'Envío gratis desde 99 €', account: 'Área del cliente', cart: 'Carrito', empty: 'Tu carrito está vacío.' },
  FR: { shop: 'Boutique', categories: 'Catégories', essentials: 'Essentiels du reef', journal: 'Journal', heroEyebrow: 'Plus qu’un loisir', heroTitle: 'L’océan, chez vous.', heroBody: 'Poissons, coraux et tout ce qu’il faut pour créer un reef sain.', explore: 'Explorer la collection', story: 'Découvrir REEF GALLERY', search: 'Que recherchez-vous ?', freeShipping: 'Livraison offerte dès 99 €', account: 'Espace client', cart: 'Panier', empty: 'Votre panier est vide.' },
  DE: { shop: 'Shop', categories: 'Kategorien', essentials: 'Reef-Essentials', journal: 'Journal', heroEyebrow: 'Mehr als ein Hobby', heroTitle: 'Der Ozean zu Hause.', heroBody: 'Fische, Korallen und alles für ein gesundes Riff.', explore: 'Kollektion entdecken', story: 'REEF GALLERY entdecken', search: 'Wonach suchen Sie?', freeShipping: 'Kostenloser Versand ab 99 €', account: 'Kundenbereich', cart: 'Warenkorb', empty: 'Ihr Warenkorb ist leer.' },
  IT: { shop: 'Negozio', categories: 'Categorie', essentials: 'Essenziali reef', journal: 'Journal', heroEyebrow: 'Più di un hobby', heroTitle: 'L’oceano, a casa.', heroBody: 'Pesci, coralli e tutto ciò che serve per creare un reef sano.', explore: 'Esplora la collezione', story: 'Scopri REEF GALLERY', search: 'Cosa cerchi per il tuo reef?', freeShipping: 'Spedizione gratuita da 99 €', account: 'Area cliente', cart: 'Carrello', empty: 'Il carrello è vuoto.' },
} as const

function Logo() { return <div className="flex items-center gap-3" aria-label="REEF GALLERY início"><span className="logo-mark"><span /></span><span className="font-display text-[21px] font-semibold tracking-[0.22em] text-[#062c43]">REEF GALLERY</span></div> }

export function StorefrontHome() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [searchOpen, setSearchOpen] = useState(false)
  const [languageOpen, setLanguageOpen] = useState(false)
  const [language, setLanguage] = useState<keyof typeof translations>('PT')
  const [favorites, setFavorites] = useState<number[]>([])
  const [cart, setCart] = useState<CartLine[]>([])
  const [cartOpen, setCartOpen] = useState(false)
  const [accountOpen, setAccountOpen] = useState(false)
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null)
  const [query, setQuery] = useState('')
  const copy = translations[language]
  const cartCount = cart.reduce((total, line) => total + line.quantity, 0)
  const searchResults = useMemo(() => query.trim() ? products.filter((product) => `${product.name} ${product.detail} ${product.category}`.toLowerCase().includes(query.toLowerCase())) : [], [query])
  const addToCart = (product: Product) => { setCart((current) => { const existing = current.find((line) => line.product.id === product.id); return existing ? current.map((line) => line.product.id === product.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { product, quantity: 1 }] }); setCartOpen(true) }
  const updateQuantity = (id: string, delta: number) => setCart((current) => current.flatMap((line) => line.product.id === id ? (line.quantity + delta > 0 ? [{ ...line, quantity: line.quantity + delta }] : []) : [line]))

  return <div className="min-h-screen overflow-hidden bg-[#f8fbfc] text-[#062c43]">
    <div className="topline">Vida marinha, na sua casa <span>·</span> {copy.freeShipping}</div>
    <header className="sticky top-0 z-40 border-b border-[#dce9ed]/80 bg-[#f8fbfc]/95 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-[1280px] items-center justify-between px-5 lg:px-10">
      <button className="icon-button mr-3 lg:hidden" aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><Logo />
      <nav className="hidden items-center gap-8 lg:flex" aria-label="Navegação principal"><a className="nav-link active" href="#loja">{copy.shop}</a><a className="nav-link" href="#categorias">{copy.categories} <ChevronDown size={13} /></a><a className="nav-link" href="#essenciais">{copy.essentials}</a><a className="nav-link" href="#journal">{copy.journal}</a></nav>
      <div className="flex items-center gap-1"><div className="language-picker"><button className="language-trigger" aria-expanded={languageOpen} onClick={() => setLanguageOpen(!languageOpen)}>{language} <ChevronDown size={12} /></button>{languageOpen && <div className="language-menu" role="listbox" aria-label="Selecionar idioma">{languages.map((item) => <button key={item.code} role="option" aria-selected={language === item.code} onClick={() => { setLanguage(item.code as keyof typeof translations); setLanguageOpen(false) }}>{language === item.code && <Check size={12} />}<span>{item.code}</span><small>{item.label}</small></button>)}</div>}</div><button className="icon-button" aria-label="Pesquisar" onClick={() => setSearchOpen(!searchOpen)}><Search size={19} strokeWidth={1.8} /></button><button className="icon-button hidden sm:inline-flex" aria-label={copy.account} onClick={() => setAccountOpen(true)}><UserRound size={19} strokeWidth={1.8} /></button><button className="icon-button relative" aria-label={copy.cart} onClick={() => setCartOpen(true)}><ShoppingBag size={19} strokeWidth={1.8} />{cartCount > 0 && <span className="cart-count">{cartCount}</span>}</button></div>
    </div>{searchOpen && <div className="search-panel"><div className="mx-auto max-w-[1280px] px-5 lg:px-10"><div className="search-box"><Search size={18} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.search} aria-label={copy.search} /><button aria-label="Fechar pesquisa" onClick={() => { setSearchOpen(false); setQuery('') }}>ESC</button></div>{searchResults.length > 0 && <div className="search-results">{searchResults.map((product) => <button key={product.id} onClick={() => { setSelectedProduct(product); setSearchOpen(false) }}><span>{product.name}</span><small>{product.price}</small></button>)}</div>}{query && !searchResults.length && <p className="py-4 text-sm text-[#64818c]">Nenhum produto encontrado.</p>}</div></div>}{menuOpen && <nav className="mobile-menu lg:hidden" aria-label="Menu mobile"><a href="#loja" onClick={() => setMenuOpen(false)}>Loja</a><a href="#categorias" onClick={() => setMenuOpen(false)}>Categorias</a><a href="#essenciais" onClick={() => setMenuOpen(false)}>Essenciais do reef</a><a href="#journal" onClick={() => setMenuOpen(false)}>Journal</a><button className="mobile-account" onClick={() => { setMenuOpen(false); setAccountOpen(true) }}><UserRound size={16} /> {copy.account}</button></nav>}</header>
    <main><section className="relative mx-auto max-w-[1280px] px-4 pt-4 sm:px-5 lg:px-10 lg:pt-6"><div className="hero-shell"><div className="hero-water-motion" aria-hidden="true" /><Image src="/images/reef-hero.png" alt="Peixes coloridos sobre um recife de coral" fill priority className="hero-image object-cover" sizes="(max-width: 1280px) 100vw, 1280px" />{HERO_VIDEO_URL && <video className="absolute inset-0 z-0 size-full object-cover" autoPlay muted loop playsInline preload="metadata" poster="/images/reef-hero.png" aria-hidden="true"><source src={HERO_VIDEO_URL} type="video/mp4" /></video>}<div className="hero-overlay" /><div className="hero-particles" aria-hidden="true"><span /><span /><span /><span /></div><div className="relative flex min-h-[540px] flex-col justify-end p-7 sm:min-h-[600px] sm:p-12 lg:min-h-[630px] lg:p-16"><p className="eyebrow text-[#a9e5e7]">{copy.heroEyebrow}</p><h1 className="mt-4 max-w-[620px] font-display text-5xl leading-[0.98] tracking-[-0.04em] text-white sm:text-7xl">{copy.heroTitle}</h1><p className="mt-6 max-w-[420px] text-[15px] leading-7 text-white/75">{copy.heroBody}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#loja" className="button-primary">{copy.explore} <ArrowRight size={16} /></a><a href="#journal" className="button-ghost">{copy.story}</a></div></div><div className="hero-note hidden sm:block"><Sparkles size={15} /> Curadoria especializada <span /></div></div></section>
      <section className="mx-auto max-w-[1280px] px-5 py-16 lg:px-10 lg:py-24" id="categorias"><div className="section-heading"><div><p className="eyebrow text-[#3f8791]">Explore por categoria</p><h2 className="section-title">Tudo para um reef <em>extraordinário.</em></h2></div><a href="#loja" className="text-link hidden sm:flex">Ver toda a loja <ArrowRight size={15} /></a></div><div className="mt-9 grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-4">{categories.map((category, index) => <a href="#loja" key={category.name} className={`category-card ${index === 0 ? 'category-card-large' : ''}`} onClick={() => setQuery(category.query)}><Image src={category.image} alt={category.name} fill className="object-cover" sizes="(max-width: 768px) 50vw, 25vw" /><div className="category-shade" /><div className="relative z-10 flex h-full flex-col justify-end p-4 sm:p-6"><span className="mb-1 text-[11px] uppercase tracking-[0.14em] text-white/70">{category.count}</span><span className="font-display text-xl tracking-[-0.02em] text-white sm:text-2xl">{category.name}</span><ArrowRight className="mt-4 text-[#a9e5e7]" size={18} /></div></a>)}</div></section>
      <section className="bg-[#eaf4f5]" id="loja"><div className="mx-auto max-w-[1280px] px-5 py-16 lg:px-10 lg:py-24"><div className="section-heading"><div><p className="eyebrow text-[#3f8791]">Escolhas da semana</p><h2 className="section-title">O melhor do <em>reef.</em></h2></div><a href="#categorias" className="text-link hidden sm:flex">Ver novidades <ArrowRight size={15} /></a></div><div className="mt-9 grid gap-5 md:grid-cols-3">{products.map((product, index) => <article className="product-card" key={product.name}><button className="product-image group w-full text-left" onClick={() => setSelectedProduct(product)}><Image src={product.image} alt={product.name} fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw" /><span className="product-tag">{product.tag}</span></button><button className={`favorite ${favorites.includes(index) ? 'is-favorite' : ''}`} aria-label={`Adicionar ${product.name} aos favoritos`} onClick={() => setFavorites((current) => current.includes(index) ? current.filter((item) => item !== index) : [...current, index])}><Heart size={17} fill={favorites.includes(index) ? 'currentColor' : 'none'} /></button><div className="pt-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-xl text-[#062c43]">{product.name}</h3><p className="mt-1 text-[12px] text-[#64818c]">{product.detail}</p></div><span className="text-sm font-semibold text-[#062c43]">{product.price}</span></div><button className="add-button" onClick={() => addToCart(product)}>Adicionar ao carrinho <ShoppingBag size={15} /></button></div></article>)}</div></div></section>
      <section className="mx-auto max-w-[1280px] px-5 py-16 lg:px-10 lg:py-24" id="essenciais"><div className="feature-banner"><div className="feature-copy"><p className="eyebrow text-[#a9e5e7]">O ritual do reef</p><h2 className="mt-4 max-w-[450px] font-display text-4xl leading-[1.05] tracking-[-0.03em] text-white sm:text-5xl">Mais do que um aquário. <em>Um ecossistema.</em></h2><p className="mt-5 max-w-[400px] text-sm leading-6 text-white/65">Equipamentos confiáveis, conhecimento e suporte para manter o seu mundo subaquático próspero.</p><a href="#loja" className="button-primary mt-8">Ver essenciais <ArrowRight size={16} /></a></div><div className="feature-stats"><div><strong>01</strong><span>Curadoria<br />sem atalhos</span></div><div><strong>02</strong><span>Entrega viva<br />e segura</span></div><div><strong>03</strong><span>Suporte de<br />aquarista</span></div></div></div></section>
      <section className="border-t border-[#dce9ed]" id="journal"><div className="mx-auto flex max-w-[1280px] flex-col items-start justify-between gap-6 px-5 py-12 sm:flex-row sm:items-center lg:px-10"><div><p className="eyebrow text-[#3f8791]">Fique por dentro</p><h2 className="mt-2 font-display text-3xl tracking-[-0.03em]">Notas do <em>oceano.</em></h2></div><div className="flex w-full max-w-[420px] border-b border-[#9fbcc2] pb-3 sm:w-[360px]"><input className="flex-1 bg-transparent text-sm outline-none placeholder:text-[#78949c]" placeholder="O seu email" aria-label="Email para newsletter" /><button aria-label="Subscrever newsletter" className="text-sm font-semibold text-[#087b88]">Subscrever <ArrowRight className="ml-1 inline" size={15} /></button></div></div></section></main>
    <footer className="bg-[#062c43] text-white"><div className="mx-auto flex max-w-[1280px] flex-col justify-between gap-10 px-5 py-12 sm:flex-row lg:px-10"><div><Logo /><p className="mt-5 max-w-[260px] text-xs leading-6 text-white/50">Aquarismo marinho premium, com curadoria e confiança.</p></div><div className="flex gap-12 text-xs text-white/60"><div className="flex flex-col gap-3"><span className="mb-1 text-[10px] uppercase tracking-[0.16em] text-[#a9e5e7]">REEF GALLERY</span><a href="#journal">Sobre nós</a><a href="#journal">Journal</a><a href="#journal">Contacto</a></div><div className="flex flex-col gap-3"><span className="mb-1 text-[10px] uppercase tracking-[0.16em] text-[#a9e5e7]">Social</span><a href="#journal">Instagram</a><a href="#journal">Pinterest</a><a href="#journal">@reefgallery</a></div></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-5 text-[10px] uppercase tracking-[0.12em] text-white/35 lg:px-10"><span>© 2026 REEF GALLERY</span><span className="text-[#a9e5e7]">@</span></div></div></footer>
    {selectedProduct && <div className="modal-backdrop" role="presentation" onClick={() => setSelectedProduct(null)}><div className="product-modal" role="dialog" aria-modal="true" aria-labelledby="product-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Fechar produto" onClick={() => setSelectedProduct(null)}><X /></button><div className="product-modal-image"><Image src={selectedProduct.image} alt={selectedProduct.name} fill className="object-cover" /></div><div className="p-6"><p className="eyebrow text-[#3f8791]">{selectedProduct.tag}</p><h2 id="product-title" className="mt-2 font-display text-3xl">{selectedProduct.name}</h2><p className="mt-2 text-sm text-[#64818c]">{selectedProduct.detail}</p><p className="mt-6 text-xl font-semibold">{selectedProduct.price}</p><button className="add-button" onClick={() => { addToCart(selectedProduct); setSelectedProduct(null) }}>Adicionar ao carrinho <ShoppingBag size={15} /></button></div></div></div>}
    {cartOpen && <div className="modal-backdrop" role="presentation" onClick={() => setCartOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-title" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-[#dce9ed] p-6"><h2 id="cart-title" className="font-display text-2xl">{copy.cart}</h2><button className="icon-button" aria-label="Fechar carrinho" onClick={() => setCartOpen(false)}><X /></button></div><div className="flex flex-1 flex-col gap-5 overflow-auto p-6">{cart.length === 0 ? <p className="py-10 text-center text-sm text-[#64818c]">{copy.empty}</p> : cart.map((line) => <div className="flex gap-3" key={line.product.id}><div className="relative size-16 shrink-0 overflow-hidden rounded"><Image src={line.product.image} alt="" fill className="object-cover" /></div><div className="min-w-0 flex-1"><p className="font-medium">{line.product.name}</p><p className="text-sm text-[#64818c]">{line.product.price}</p><div className="mt-2 flex items-center gap-2"><button className="quantity-button" aria-label="Diminuir quantidade" onClick={() => updateQuantity(line.product.id, -1)}><Minus /></button><span className="w-5 text-center text-sm">{line.quantity}</span><button className="quantity-button" aria-label="Aumentar quantidade" onClick={() => updateQuantity(line.product.id, 1)}><Plus /></button></div></div></div>)}</div>{cart.length > 0 && <div className="border-t border-[#dce9ed] p-6"><div className="mb-4 flex justify-between font-semibold"><span>Total</span><span>€ {cart.reduce((total, line) => total + Number(line.product.price.replace('€ ', '').replace('.', '').replace(',', '.')) * line.quantity, 0).toFixed(2).replace('.', ',')}</span></div><button className="button-primary w-full justify-center" onClick={() => setCartOpen(false)}>Continuar a explorar <ArrowRight size={16} /></button></div>}</aside></div>}
    {accountOpen && <div className="modal-backdrop" role="presentation" onClick={() => setAccountOpen(false)}><div className="account-modal" role="dialog" aria-modal="true" aria-labelledby="account-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" aria-label="Fechar área do cliente" onClick={() => setAccountOpen(false)}><X /></button><UserRound className="text-[#087b88]" /><h2 id="account-title" className="mt-4 font-display text-3xl">{copy.account}</h2><p className="mt-2 text-sm leading-6 text-[#64818c]">Acompanhe os seus pedidos, favoritos e dados de aquarista.</p><button className="button-primary mt-6 w-full justify-center" onClick={() => setAccountOpen(false)}>Entrar na sua conta <ArrowRight size={16} /></button><button className="mt-3 w-full text-sm font-semibold text-[#087b88]" onClick={() => setAccountOpen(false)}>Criar uma conta</button></div></div>}
  </div>
}
export default StorefrontHome
